# HomesThatWork Custom Messages and Configuration File
messages:
    prefix: "&7[&cHomesThatWork&7]"
    # not-a-command-error is for /htw help only.
    # Does not display a message for general invalid commands.
    not-a-command-error:  "That is not a vaild HTW Command."
    invalid-subcommand: "That is not a valid subcommand!"
    admin-errors:
        offline: "Given Player is Offline: Last known player named %arg1%: "
        invalid-player: "That player does not exist."
        noperm: "You do not have permission to view other players' information."
    player-errors:
        max-homes-set:  "Maxmium number of homes set."
        home-already-exists: "Home already exists."

        # %d --> the number of homes that you must delete.
        # %s --> the "s" in homes if there are multiple.
        too-many-homes: "Too many homes set. You must delete %d home%s."
        home-not-exist: "Home does not exist."
        no-homes-set: "No homes set."
        home-remove-fail: "Unable to remove home data - please contact an administrator."
        no-previous-loc: "No previous location recorded!"
    player-msgs:
        home-set-success: "Home successfully set"
        home-remove-success: "Home successfully removed"
    permission-msgs:
        no-command-perm: "You do not have permission for this command."
        no-interdimensional-perm: "You do not have permission for interdimensional homes."
    file-errors:
        home-set-error: "Unable to save home - please contact an administrator."
        corrupt-home-data: "Home data corrupted - please contact an adminstrator."
        last-location-save-error: "Unable to save last location - please contact an administrator."
    command-msgs:
        delhome:
            description: "Deletes an existing home from record"
        goback:
            description: "Go back to the last location you were before your last /home command"
        home:
            description: "Teleport to a specified home point. If no home is specified, the default is used (see '/sethome')"
        sethome:
            description: "Assigns current location to home name. If no name is specified, then the current location is set as the default home"
        listhomes:
            description: "Lists homes of a specified player"
        homeinfo:
            description: "Lists information about a specified home"
        htw-reload:
            description: "Reloads the HomesThatWork configuration file"
            success: "The HomesThatWork configuration file was reloaded!"
        htw:
            description: "Main plugin command. See /htw help for command list"
